#!/bin/sh
RED='\033[0;31m'
NC='\033[0m'

branch_name=$(git rev-parse --abbrev-ref HEAD)

# List of protected branches
PROTECTED_BRANCHES="develop main"

for protected in $PROTECTED_BRANCHES; do
  if [ "$branch_name" = "$protected" ]; then
    echo "${RED}Pushing to '${branch_name}' is not allowed! Please create a merge request.${NC}"
    exit 1
  fi
done

echo "Push is allowed, continuing..."
